services:
  # Запуск Angular
  frontend-angular:
    container_name: angular
    build:
      context: ./frontend/angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - angular:/app/dist
    hostname: host.docker.internal
    command: npm run build:prod
    networks:
      - appTodoLists

    # Запуск Next
  frontend-next:
    container_name: next
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
    volumes:
      - next:/app/.next
    hostname: host.docker.internal
    ports:
      - 3000:3000
    command: npm run start:prod
    depends_on:
      - db
    networks:
      - appTodoLists

  # Запуск Nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - angular:/usr/share/nginx/html/angular
      - next:/usr/share/nginx/html/next
      - ssl-certs:/etc/nginx/ssl
    depends_on:
      - frontend-angular
      - frontend-next
    networks:
      - appTodoLists

  # Запуск Express
  backend-express:
    container_name: node-express
    build:
      context: ./backend/express
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    environment:
      - PORT=8443
    hostname: host.docker.internal
    volumes:
      - express:/app/dist
      - ssl-certs:/app/ssl
    command: npm run start:prod
    depends_on:
      - db
    networks:
      - appTodoLists
    restart: on-failure

  # Запуск Postgres
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    hostname: host.docker.internal
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appTodoLists

  # Запуск pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dpage-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: den073777@ya.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - appTodoLists

networks:
  appTodoLists:
    driver: bridge

volumes:
  express:
  angular:
  next:
  pgdata:
  ssl-certs:
